### ISSUE TITLE
Path gets doubled when loading tasks from a sub-folder

### ISSUE THREAD

**Issue by shiitake** [hontas/gulp-task-loader#22]
I'm trying to point my task loader to a specific folder ./tasks/dev

`gulp.task("default", function(){
    require('gulp-task-loader')(
        { dir: './tasks/dev/',      
            settings: settings,
            handleErrors: handleErrors
        });
 });`

But when I run the task it actually doubles the 'dev' part of the folder path. 

[10:14:37] Error: Cannot find module 'C:\Git\my-project\tasks**\dev\dev\**browser-sync.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at loadTask (C:\Git\my-project\node_modules\gulp-task-loader\index.js:50:14)
    at loadTasks (C:\Git\my-project\node_modules\gulp-task-loader\index.js:71:4)
    at C:\Git\my-project\node_modules\gulp-task-loader\index.js:76:6
    at Array.forEach (native)
    at loadTasks (C:\Git\my-project\node_modules\gulp-task-loader\index.js:75:6)
    at module.exports (C:\Git\my-project\node_modules\gulp-task-loader\index.js:81:2)

This actually look very similar to https://github.com/hontas/gulp-task-loader/issues/12 and https://github.com/devbridge/Front-End-Toolkit/issues/56

I'm running version 1.4.2

**Comment by hontas** [comment]
@shiitake sorry bout the late response. Have you tried it without the trailing slash?
Should work anyway of course, but please try that first.

**Comment by hontas** [comment]
fixed in 1e707b4 (v1.4.4)

**Comment by ghost** [comment]
Hi @hontas, after update I have the same problem. I can't point my task to a sub-folder, because task loader then searches that folder in sub-folder...

When I use: require('gulp-task-loader')('gulp/css');
And then I get
Error: Cannot find module 'C:\Web\my-project\gulp**\css\css\**compile-scss.js'
Tested with v1.4.4

When I use: require('gulp-task-loader')('gulp');
It finds task named "css:compile-scss"
and it works, but I really would like to use subfolder approach so i can manage my tasks better, not all in one folder.

Thanks

**Comment by hontas** [comment]
Hi @AndriusZid it seems both wrong and fine. Hard to tell, could you please give me some more info on your directory structure?
Your second attempt suggests that it works as it should, because it loads subfolder `css` as namespace and then task `compile-css`. But again, it's hard to draw any conclusions without more context.
Not sure if I could duplicate this on the mac.. it'd be really helpful if you could write a failing test for this.
